export const PLAYER_ONE = 0
export const PLAYER_TWO = 1
export const DEFAULT_GRID_SIZE = 5
export const ATTACK = 'Pick a square to attack'
export const PLACEMENT_HINT = 'Select a ship to move it to a new location.'
export const MISS = 'miss'
export const HIT = 'hit'
export const ALREADY_TAKEN = 'already taken'
export const SUNK = 'sunk'
export const GAME_OVER = 'game over'
